depth: 48
patch_size: 2
num_heads: 24
hidden_size_x: 3072
hidden_size_y: 1536
mlp_ratio_x: 4.0
mlp_ratio_y: 4.0
in_channels: 12
qk_norm: true
qkv_bias: false
out_bias: true
patch_embed_bias: true
timestep_mlp_bias: true
timestep_scale: 1000.0
t5_feat_dim: 4096
t5_token_length: 256
rope_theta: 10000.0